# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Liste < Formula
  desc "Portable CLI roadmap tracker for humans and AI agents"
  homepage "https://github.com/pufferhaus/liste"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pufferhaus/liste/releases/download/v1.0.0/liste_1.0.0_darwin_amd64.tar.gz"
      sha256 "586923b96619b32a1420aa17ecef933bba28f6d13683effb247ae43accd34fed"

      define_method(:install) do
        bin.install "liste"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pufferhaus/liste/releases/download/v1.0.0/liste_1.0.0_darwin_arm64.tar.gz"
      sha256 "49cb6ef64fba9129968b5e12d250789479ddde0ba8b0375f57ab3191432fe430"

      define_method(:install) do
        bin.install "liste"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pufferhaus/liste/releases/download/v1.0.0/liste_1.0.0_linux_amd64.tar.gz"
      sha256 "b890908f138c59d7811a8f35aa1b30cc63d6027b974c38495fdc8c9a85c2248d"
      define_method(:install) do
        bin.install "liste"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pufferhaus/liste/releases/download/v1.0.0/liste_1.0.0_linux_arm64.tar.gz"
      sha256 "23a9140d4ef88071c498e0e21d7cf69d2b627f1dacccfc70d73266c483d33e74"
      define_method(:install) do
        bin.install "liste"
      end
    end
  end

  def caveats
    <<~EOS
      Install Claude Code skills for AI agents:
        liste skills install

      Then add to ~/.claude/CLAUDE.md:
        At the start of every session, invoke the liste:session-start skill.

      Docs: https://github.com/pufferhaus/liste
    EOS
  end

  test do
    system "#{bin}/liste", "version"
  end
end
